# Generated by Django 4.2.7 on 2025-11-12 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("multiplicador_puntos", models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("TI", "Tarjeta de Identidad"),
                            ("PA", "Pasaporte"),
                            ("NIT", "NIT"),
                        ],
                        default="CC",
                        max_length=3,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=20, unique=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("O", "Otro"),
                            ("N", "Prefiero no decir"),
                        ],
                        max_length=1,
                    ),
                ),
                ("telefono", models.CharField(max_length=20)),
                ("telefono_alternativo", models.CharField(blank=True, max_length=20)),
                ("email_alternativo", models.EmailField(blank=True, max_length=254)),
                (
                    "direccion",
                    models.CharField(default="Sin especificar", max_length=255),
                ),
                ("barrio", models.CharField(blank=True, max_length=100)),
                ("ciudad", models.CharField(default="Bogotá", max_length=100)),
                (
                    "departamento",
                    models.CharField(default="Cundinamarca", max_length=100),
                ),
                ("codigo_postal", models.CharField(blank=True, max_length=10)),
                ("nivel", models.CharField(default="Bronce", max_length=10)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                ("acepta_promociones", models.BooleanField(default=True)),
                ("acepta_notificaciones", models.BooleanField(default=True)),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Notas internas sobre el cliente"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_factura", models.CharField(max_length=50)),
                ("fecha_compra", models.DateField()),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sucursal", models.CharField(max_length=100)),
                ("registrada", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Referido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_referencia", models.DateTimeField(auto_now_add=True)),
                ("puntos_otorgados", models.IntegerField(default=0)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referidos_hechos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "referido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referidos_recibidos",
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Punto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntos_obtenidos", models.IntegerField()),
                ("fecha_obtencion", models.DateTimeField(auto_now_add=True)),
                ("tipo", models.CharField(default="Compra", max_length=50)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.factura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Premio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("puntos_requeridos", models.IntegerField()),
                ("fecha_otorgado", models.DateField(auto_now_add=True)),
                ("entregado", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
    ]
