# Generated by Django 4.2.7 on 2025-11-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoPremio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField()),
                ("puntos_requeridos", models.IntegerField()),
                ("disponible", models.BooleanField(default=True)),
                ("imagen_url", models.URLField(blank=True)),
                ("stock", models.IntegerField(default=999)),
            ],
            options={
                "verbose_name": "Catálogo de Premio",
                "verbose_name_plural": "Catálogo de Premios",
                "ordering": ["puntos_requeridos"],
            },
        ),
        migrations.AddField(
            model_name="premio",
            name="catalogo_premio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clientes.catalogopremio",
            ),
        ),
    ]
