# Generated by Django 4.2.7 on 2025-11-12 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_catalogopremio_premio_catalogo_premio"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="codigo_referido",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="referido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mis_referidos",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="notas",
            field=models.TextField(blank=True),
        ),
    ]
